# Site settings
title: Data Science Manifesto
email: data-science-manifesto@googlegroups.com
description: > # this means to ignore newlines until "baseurl:"
  Manifesto of Agile, Static typing and Functional principles applied in building Data Science applications.
baseurl: "" # the subpath of your site, e.g. /blog/
#url: "http://datasciencemanifesto.com" # the base hostname & protocol for your site
#twitter_username: jekyllrb
#github_username:  gm-spacagna

# Build settings
#name: Data Science Manifesto
#markdown: redcarpet

#highlighter: pygments

#baseurl: /data-science-manifesto
